### ISSUE TITLE
on_touch not responding

### ISSUE THREAD

**Issue by casper91** [synbioz/introduction_motiongame#1]
I can't it to work on IOS simulator. Nothing happens when push one of the names.
It is like on_touch not registering the push? Is it something wrong with my simulator or the code?

**Comment by nicolaslechenic** [comment]
Sorry but I can't reproduce this behavior, everything works fine for me. The problem probably happens on your side but I come to you if I have an answer.

**Comment by casper91** [comment]
I used motion-game v. 1.1 and updating it to v. 1.1.1 fixed the problem.

**Comment by nicolaslechenic** [comment]
Ok, this is a known issue [here](https://github.com/HipByte/motion-game/issues/14).
